dotnet mvc Core 1/WebApplication3/Models/Client.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication3.Models
{
	public class Client
	{

		public Client() { }

		public Client(int id, string name)
		{
			this.Id = id;
			this.Name = name;
		}

		public int Id { get; set; }

		public string Name { get; set; }


		public class ViewModell
		{
			public IEnumerable<Client> ClientDetailList { get; set; }
		}

	}
}

dotnet mvc Core 1/WebApplication3/Models/ErrorViewModel.cs
using System;

namespace WebApplication3.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

dotnet mvc Core 1/WebApplication3/Models/Item.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace WebApplication3.Models
{
    public class Item
    {
        [Required]
        [Display(Name = "Könummer")]
		public int Id { get; set; }


        [Required]
        [Display(Name = "Namn")]
        public string Name { get; set; }

		public Item()
		{
			Id = 1;
			Name = "Test Modell";
		}

	}
}

dotnet mvc Core 1/WebApplication3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication3.Models;

using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;



namespace WebApplication3.Controllers
{
	public class HomeController : Controller
	{
		public IActionResult Index()
		{
			string s = "Text i en sessionsvariabel på Index-hem-sidan";
			HttpContext.Session.SetString("indextext", s);
            ViewBag.text = s;
            return View();
		}


		public IActionResult Omoss()
		{
            string s = "Text i en sessionsvariabel på Omoss-sidan";
            HttpContext.Session.SetString("omosstext", s);
            ViewData["Message"] = "Text som har sparats i ViewData";
			ViewBag.text1 = "Tect som har sparats i ViewBag";
            ViewBag.text2 = s;
            return View();
		}


		public IActionResult Extra()
		{
			string s2 = HttpContext.Session.GetString("indextext");
			ViewBag.indextext = s2;
            s2 = HttpContext.Session.GetString("omosstext");
            ViewBag.omosstext = s2;
            return View();
		}


		public IActionResult Modell()
		{
            Item myitem = new Item();
            //myitem.Name = "hÄR ÄR NAMNET ÄNDRAT";
            string s1 = JsonConvert.SerializeObject(myitem);
            HttpContext.Session.SetString("modell", s1);
            ViewBag.jsonsträng1 = s1;
            return View(myitem);
        }


		public IActionResult Modell2()
		{
            string s2 = HttpContext.Session.GetString("modell");
            ViewBag.jsonsträng2 = s2;
            Item myitem2 = JsonConvert.DeserializeObject<Item>(s2);
            return View(myitem2);
        }


		public IActionResult Client()
		{

			List<Client> clients = new List<Client>
			{
				new Client(1, "Axis AB"),
				new Client(2, "Handi AB"),
				new Client(3, "Sandi AB"),
				new Client(4, "Britt Marie ek")
			};

			ViewData["clients-in-list"] = clients;



			List<Client> clients2 = new List<Client>
			{
				new Client(1, "Beev"),
				new Client(2, "Naaast"),
				new Client(3, "Craast"),
				new Client(4, "Ubiin")
			};

			ViewBag.clients = clients2;


			List<Client> clients3 = new List<Client>
			{
				new Client(1, "Asdfg"),
				new Client(2, "Qwert"),
				new Client(3, "Zxcvb"),
				new Client(4, "Uiopå")
			};


            Client.ViewModell vm = new Client.ViewModell();
            vm.ClientDetailList = clients3;

			return View(vm);

		}

        public IActionResult Itemlist1()
        {
            var itemlist = new List<Item>();
            itemlist.Add(new Item { Id = 1, Name = "Bertile" });
            itemlist.Add(new Item { Id = 2, Name = "Louise" });

            string s = JsonConvert.SerializeObject(itemlist);

            ViewBag.jsonsträng3 = s;

            HttpContext.Session.SetString("itemlist1", s);
            return View(itemlist);
        }


        public IActionResult ItmlistFromSession()
        {
            var itemlist = new List<Item>();
            string s = HttpContext.Session.GetString("itemlist1");
            if(s != null  || s == "")
            {
                itemlist = JsonConvert.DeserializeObject<List<Item>>(s);
            }
            
            return View(itemlist);
        }





        [HttpGet]
        public IActionResult Form1()
        {
            return View();
        }



        [HttpPost]
        public IActionResult Form1(IFormCollection fc)
        {
            string s = fc["textexempel"];
            ViewBag.form1 = s;
            return View();
        }





        [HttpGet]
        public IActionResult Form2()
        {
            return View();
        }



        [HttpPost]
        public IActionResult Form2(IFormCollection fc)
        {
            string s = fc["textexempel"];
            ViewBag.form2 = s;
            return View();
        }




        [HttpGet]
        public IActionResult Form3()
        {
            return View();
        }



        [HttpGet]
        public IActionResult Form4([FromQuery]string form3text)
        {
            ViewBag.form4 = form3text;
            return View();
        }




        public IActionResult SignIn()
        {
            return View();
        }



        public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

dotnet mvc Core 1/WebApplication3/Controllers/NewItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class NewItemController : Controller
    {
        // GET: NewItem
        public ActionResult Index()
        {
            var item = new Item();
            string s = HttpContext.Session.GetString("create");
            item = JsonConvert.DeserializeObject<Item>(s);
            ViewBag.Id = item.Id;
            ViewBag.Name = item.Name;
            return View();
        }

        // GET: NewItem/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: NewItem/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NewItem/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                var item = new Item();
                item.Name = collection["Name"];
                item.Id = Convert.ToInt32( collection["Id"] );
                string s = JsonConvert.SerializeObject(item);
                HttpContext.Session.SetString("create", s);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: NewItem/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: NewItem/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: NewItem/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: NewItem/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

dotnet mvc Core 1/WebApplication3/Views/Home/Client.cshtml
@model WebApplication3.Models.Client.ViewModell


@{
    ViewData["Title"] = "Client";
}

<h1>Client</h1>


<p>Listan från ViewData: </p>

@{
    IEnumerable<WebApplication3.Models.Client> clients = (IEnumerable<WebApplication3.Models.Client>)ViewData["clients-in-list"];
}
<table>
    <tr>
        <th>Id </th>
        <th>Name</th>
    </tr>

    @foreach (Client client in clients)
    {
        <tr>
            <th>@client.Id</th>
            <th>@client.Name</th>
        </tr>
    }
</table>

<p>Listan från ViewBag: </p>

@{
    IEnumerable<WebApplication3.Models.Client> clients2 = (IEnumerable<WebApplication3.Models.Client>)ViewBag.clients;
}
<table>
    <tr>
        <th>Id </th>
        <th>Name</th>
    </tr>

    @foreach (Client client in clients2)
    {
        <tr>
            <th>@client.Id</th>
            <th>@client.Name</th>
        </tr>
    }
</table>


<p>Listan från ViewModell: </p>
<table>
    <tr>
        <th>Id </th>
        <th>Name</th>
    </tr>

    @foreach (WebApplication3.Models.Client client in Model.ClientDetailList)
    {
        <tr>
            <th>@client.Id</th>
            <th>@client.Name</th>
        </tr>
    }
</table>

dotnet mvc Core 1/WebApplication3/Views/Home/Extra.cshtml
@{
    ViewData["Title"] = "Extra";
}

<h1>Extra</h1>

<p>Sessionvariabel:</p>
<p>Sessionvariabel-kommer från Index: @ViewBag.indextext</p>
<p>Sessionvariabel-kommer från Omoss: @ViewBag.omosstext</p>

dotnet mvc Core 1/WebApplication3/Views/Home/Form1.cshtml
@{
    ViewData["Title"] = "Form1";
}

<h1>Form1- formulär</h1>

@using (Html.BeginForm())
{
    @Html.TextBox("Textexempel");
    <input type="submit" value="Skicka in" class="btn-primary" />
}

<p>
    Här nedan kommer resultatet:
    <br />
    @ViewBag.form1
</p>

dotnet mvc Core 1/WebApplication3/Views/Home/Form2.cshtml
@{
    ViewData["Title"] = "Form2";
}

<h1>Form2</h1>


<form action="/Home/Form2" method="post">
    <input id="Textexempel" name="Textexempel" type="text" value="" />    
    <input type="submit" value="Skicka in" class="btn-primary" />

  </form>

<p>
    @ViewBag.form2

</p>

dotnet mvc Core 1/WebApplication3/Views/Home/Form3.cshtml
@{
    ViewData["Title"] = "Form3";
}

<h1>Form3</h1>

<form action="/Home/Form4" method="get" name="form3text2">
    <br>
    Text:
    <br>
    <input id="form3text" type="text" name="form3text" value="">
    <br><br>
    <input type="submit" value="Submit">
    <br><br>

    <input type="radio" name="gender" value="male" checked> Male<br>
    <input type="radio" name="gender" value="female"> Female<br>
    <input type="radio" name="gender" value="other"> Other

    <br><br>
    Birthday:
    <input type="date" name="bday">


    <br /><br /><br />
    <input type="submit" value="Skicka in" class="btn-dark">
</form>

dotnet mvc Core 1/WebApplication3/Views/Home/Form4.cshtml
@{
    ViewData["Title"] = "Form4";
}

<h1>Form4</h1>
<p>

    Följande har vi hämtat från form3:
    <br />

    @ViewBag.form4
    <br />
    <br />


</p>

dotnet mvc Core 1/WebApplication3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="slider">
    <h1 class="display-4">Välkomna</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<p>
    @ViewBag.text
</p>
<div class="text-center">

</div>

dotnet mvc Core 1/WebApplication3/Views/Home/Itemlist1.cshtml
@model IEnumerable<WebApplication3.Models.Item>

@{
    ViewData["Title"] = "Itemlist1";
}

<h1>Itemlist1</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>
<p>
    Här skriver ut json-convertinnehållet som ska skickas:
    <br />
    @ViewBag.jsonsträng3
</p>

dotnet mvc Core 1/WebApplication3/Views/Home/ItmlistFromSession.cshtml
@model IEnumerable<WebApplication3.Models.Item>

@{
    ViewData["Title"] = "ItmlistFromSession";
}

<h1>ItmlistFromSession</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

@foreach (var item in Model)
{
<ul>
    <li>@Html.DisplayNameFor(model => model.Id): @Html.DisplayFor(modelItem => item.Id)    </li>
    <li>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(modelItem => item.Name)    </li>
</ul>
}

dotnet mvc Core 1/WebApplication3/Views/Home/Modell.cshtml
@model WebApplication3.Models.Item
@{
    ViewData["Title"] = "Modell";
}

<h1>Modell</h1>

<p>
	Detta är modellen 
	<br>
	Id: @Model.Id
	<br>
	Name: @Model.Name

</p>
<p>
    Här nedan skriver vi ut JSON-convert-innehållet som ska skickas:
    <br>
    @ViewBag.jsonsträng1

</p>

dotnet mvc Core 1/WebApplication3/Views/Home/Modell2.cshtml
@model WebApplication3.Models.Item

@{
    ViewData["Title"] = "Modell2";
}

<h1>Modell2</h1>

<div>
    <h4>Item</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<p>
    Här nedan skriver vi ut JSON-convert-innehållet som kommer via session:
    <br>
    @ViewBag.jsonsträng2

</p>

dotnet mvc Core 1/WebApplication3/Views/Home/Omoss.cshtml
@{
    ViewData["Title"] = "Omoss";
}

<h1>Omoss</h1>
<h2>@ViewData["Message"]</h2>
<h3>@ViewBag.text1</h3>
<h3>@ViewBag.text2</h3>

dotnet mvc Core 1/WebApplication3/Views/Home/SignIn.cshtml
@{
    ViewData["Title"] = "SignIn";
}

<h1>SignIn</h1>

dotnet mvc Core 1/WebApplication3/Views/NewItem/Create.cshtml
@model WebApplication3.Models.Item

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

dotnet mvc Core 1/WebApplication3/Views/NewItem/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index NewItem</h1>

<p>
    Id: @ViewBag.Id
    <br />
    Namn: @ViewBag.Name

</p>

dotnet mvc Core 1/WebApplication3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication3</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white-112 border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication3</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Omoss">Om Oss</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Extra">Extra</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Modell">Modell</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Modell2">Modell2</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Client">Client</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Itemlist1">Itemlist1</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ItmlistFromSession">ItmlistFromSession</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Form1">Form1</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Form2">Form2</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NewItem" asp-action="Create">NewItemCreate</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Form3">Form3</a>
                        </li>



                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="SignIn">SignIn</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - WebApplication3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>